### ISSUE TITLE
Is there a way to control the camera with this library?

### ISSUE THREAD

**Issue by LaundroMat** [kutu/pyirsdk#1]
I'm looking for a means to control the replay camera with Python; can it be done with this SDK implementation?

Thanks,

Mathieu

**Comment by kutu** [comment]
you can switch between cameras, not control it

**Comment by LaundroMat** [comment]
So there is no way tp send messages (like in the [C# SDK implementation](https://github.com/vipoo/iRacingSDK.Net#sending-messages-to-the-game)? What would I need to be able to do so?

**Comment by LaundroMat** [comment]
That's indeed what I meant to ask; how can I do this? I can't figure out how to set variables, only how to read them.

**Comment by kutu** [comment]
https://github.com/kutu/pyirsdk/blob/master/irsdk.py#L302
`ir.cam_switch_pos(1, 1)`

**Comment by LaundroMat** [comment]
Great, thanks. (And thanks for this library!)
