### ISSUE TITLE
Read .ibt file

### ISSUE THREAD

**Issue by agalera** [kutu/pyirsdk#10]
I would like to know if it is possible to use this project to read the ibt files (telemetry) since I imagine they are quite similar.

I can read data from the file, but it only shows me the first sample and I don't know how to move it to the next ones ...

```python
import irsdk
ir = irsdk.IRSDK()
ir.startup(test_file='test.ibt')
```

**Comment by kutu** [comment]
it is possible
https://github.com/kutu/pyirsdk/blob/33a10d9942bb13edab53640dd71052a9335a5325/irsdk.py#L610
