### ISSUE TITLE
mmap.mmap() returns "TypeError: an integer is required (got type str)"

### ISSUE THREAD

**Issue by thomas-cnrt** [kutu/pyirsdk#11]
Hello,

I have just installed pyirsdk and I tried to run the basics example : 

**import irsdk
ir = irsdk.IRSDK()
ir.startup()
print(ir['Speed'])**

And I get the following error : 

~/.local/lib/python3.6/site-packages/irsdk.py in startup(self, test_file, dump_to)
    354                 self.__is_using_test_file = True
    355             else:
--> 356                 self._shared_mem = mmap.mmap(0, MEMMAPFILESIZE, MEMMAPFILE, access=mmap.ACCESS_READ)
    357
    358         if self._shared_mem:

**TypeError: an integer is required (got type str)**

Do you have any idea how I can fix it ?

**Comment by kutu** [comment]
you are using linux
iRacing only works under Windows
