### ISSUE TITLE
CarClassShortName is None during multiclass replay

### ISSUE THREAD

**Issue by lowlyocean** [kutu/pyirsdk#12]
Hello- noticed that when a replay of a multi-class session is running, the 'CarClassShortName' property for a driver will return as None. Seems to only be the case during a replay. Just wanted to confirm whether it's because of the data made available by iRacing? Here is the usage:

https://github.com/Fuzzwah/race-info/blob/master/race-info.py#L230

**Comment by kutu** [comment]
make a dump file with `irsdk --dump qwe.bin` and check if in raw data its there or not

**Comment by lowlyocean** [comment]
Thanks for the quick reply - looks indeed like there's no value for CarClassShortName in the raw data
