### ISSUE TITLE
iRacing Shared memory information

### ISSUE THREAD

**Issue by geek-slt** [kutu/pyirsdk#13]
Hello, I found your code for obtaining iRacing telemetry data on Github. I want to DIY a dashboard and need to obtain iRacing telemetry data, but I don’t have a parsing document for iRacing shared memory. Could you please give me? Looking forward to your help

**Comment by kutu** [comment]
https://members.iracing.com/jforum/posts/list/1470675.page

**Comment by geek-slt** [comment]
Thank you very much for your answers. I tried to obtain iRacing telemetry data through shared memory. I set the shared memory name to "Local\\IRSDKMemMapFileName", and then defined a structure to parse the data, but the parsed data is Wrong, why is this




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kutu/pyirsdk"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 晚上6:49
收件人:&nbsp;"kutu/pyirsdk"<pyirsdk@noreply.github.com&gt;;
抄送:&nbsp;"1151144104"<1151144104@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kutu/pyirsdk] iRacing Shared memory information (#13)





 
https://members.iracing.com/jforum/posts/list/1470675.page

**Comment by geek-slt** [comment]
I took a look at the official routines and found that there is a section of irsdk_header before the real telemetry data (AirDensity, AirPressure, AirTemp...). This should be the header. Does this mean I need to add before the structure of the telemetry data On the header structure?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kutu/pyirsdk"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 晚上6:49
收件人:&nbsp;"kutu/pyirsdk"<pyirsdk@noreply.github.com&gt;;
抄送:&nbsp;"1151144104"<1151144104@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kutu/pyirsdk] iRacing Shared memory information (#13)





 
https://members.iracing.com/jforum/posts/list/1470675.page
