### ISSUE TITLE
How do I use a bin file with developing purposes

### ISSUE THREAD

**Issue by mjimeneztardos** [kutu/pyirsdk#16]
Hello,
thank you rally much for this big contribution to the racing world. I want to develop a tool for my SimRacing team, but I don't have iRacing, so I'm really keen on using a data.bin file to debug the code before using it with the drivers.

My question is, how do I simulate the time in IRSDK with this mode of test_file? I mean, I can print the speed for example, just by doing ir['Speed'], but it says 0.0 all the time. How can I move forward in the recorded time?

Thank you very much.

**Comment by kutu** [comment]
you cant, dump file is just like one frame snapshot
to see speed value non 0.0, you need to dump file while driving at some speed
