### ISSUE TITLE
"TreadRemaining" always returns "100%, 100%, 100%".

### ISSUE THREAD

**Issue by lanmaster53** [kutu/pyirsdk#19]
I am using the pyirsdk to build a dashboard interface and I always get "100%, 100%, 100%" for the "TreadRemaining" property of each tire. I know that this info only updates after a pit (to replicate crew inspection), but even when I run a bunch of laps, go into the pits, change tires, leave the pits, and see that the Black Box has updated with the tire wear numbers, the API is still giving me the 3x 100%s. Any idea why this is happening? I am running the DW12 in a Practice session.

Thanks!

**Comment by kutu** [comment]
blackbox uses this variables https://github.com/kutu/pyirsdk/blob/master/vars.txt#L127

**Comment by lanmaster53** [comment]
Oh wow. Brilliant! Thanks!
