### ISSUE TITLE
What is csMode for?

### ISSUE THREAD

**Issue by LaundroMat** [kutu/pyirsdk#2]
The csMode class (irsdk.py, [line 156](https://github.com/kutu/pyirsdk/blob/2279290c826799852a5669f5b4ae865fcec02a8d/irsdk.py#L156)) seems to remain unused in the rest of the lib.

Is there a way to tell iRacing to use one of these "auto-director" modes for a replay?

**Comment by kutu** [comment]
investigate c code from irsdk 1.07.zip first
http://members.iracing.com/jforum/posts/list/1470675.page
its called csMode origianlly there

csMode is used for auto-director mode
focus on crashes, incidents, leader
