### ISSUE TITLE
Advance the tick on IBT file?

### ISSUE THREAD

**Issue by jasondilworth56** [kutu/pyirsdk#20]
Hi, thanks for all the hard work.

I wanted to move from my rig to development machine for some testing, and I've ported over to `IBT` to do that with an ibt file. I can't see an obvious way to advance the tick on that ibt file – am I missing something or is it just not possible?

**Comment by kutu** [comment]
https://github.com/kutu/pyirsdk/blob/master/irsdk.py#L699
index is tick

**Comment by jasondilworth56** [comment]
Star, thanks 👍
