### ISSUE TITLE
Question regarding `CarIdxEstTime`

### ISSUE THREAD

**Issue by Yuvix25** [kutu/pyirsdk#23]
Is this setting:  
`CarIdxEstTime                     Estimated time to reach current location on track, s`  
talking about the estimated time for me to reach the position of the other cars (by index), or the estimated time for them to reach that position?

**Comment by kutu** [comment]
this value never worked

**Comment by Yuvix25** [comment]
Currently I have assumed that it is the est time for me to get there, and it served me well, but there might be some problems when there are bigger pace differences so that's why I've asked.  
So you're sure it's not working?

**Comment by Yuvix25** [comment]
And even if it has problems, do you know the answer to the original question?
