### ISSUE TITLE
Documentation of "indexed" variables? 

### ISSUE THREAD

**Issue by codygulley** [kutu/pyirsdk#24]
The name of these  indexed variables is a bit misleading.  - e.g. `CarIdxBestLapNum`, `CarIdxBestLapTime`, `CarIdxLastLapTime`

I've tried accessing via `ir['CarIdxBestLapNum']` and `ir['CarIdxBestLapNum', 0]` however I am always ever returned arrays of -1 or an error if the latter is tried.  It is an array that is returned implying this is a list of all cars bestLapTime not a specific car index's lap time and not a specific provided car index?

Documentation currently says "Cars best lap number". "All cars best lap number" would be more precise.

Can you please update the vars.txt with that info.

**Comment by kutu** [comment]
`ir['CarIdxBestLapNum'][0]` caridx=0 value
if its -1, then its not set / no data / car not in the world

look at `CarIdxTrackSurface` values in practice, so you can see how it works

i dump documentation of variables directly from iracing api (vars.txt file), i dont write this text myself
