### ISSUE TITLE
Getting logged in users ID

### ISSUE THREAD

**Issue by zane-shus** [kutu/pyirsdk#25]
I am trying to get the iracing ID of the logged in user.  I assumed this would do it: PlayerCarIdx

```
        t = ir['PlayerCarIdx']
        print('players iracingid:', t)
```

But that only give me 0. (I joined a Official Practice session and ran it).  My other code works ok.

Am I reading that description wrong?

**Comment by kutu** [comment]
`PlayerCarIdx`  is an index in a list of drivers
do one of this
`ir['DriverInfo']['DriverUserID']`
`ir['DriverInfo']['Drivers'][ir['PlayerCarIdx']]['UserID']`
`ir['DriverInfo']['Drivers'][ir['DriverInfo']['DriverCarIdx']]['UserID']`
