### ISSUE TITLE
Is there any metric that measures time for every sector?

### ISSUE THREAD

**Issue by nineunderground** [kutu/pyirsdk#26]
I see at live sector times, but not sector attributes available apart from distances.
So, as far as I see, there are no metrics that are saving the sector times. Am I right?

Thus, all I can do is to get the lap time from _ir['LapLastLapTime']_ and do some estimations using the _ir['lapDistPct'], ir['SplitTimeInfo']['Sectors']_ and the current time which I use the value from _ir['SessionTime']_

**Comment by kutu** [comment]
> So, as far as I see, there are no metrics that are saving the sector times. Am I right?

yes

you will only need lapDistPct, SessionTime and Sectors, and do some linear approximation
some people did that, and reported on old forum, that their sector time never match in-game one
