### ISSUE TITLE
How to get speed of a specific car ID 

### ISSUE THREAD

**Issue by kstrycharz** [kutu/pyirsdk#28]
How would I get the live speed of a specific carID?? Is it possible to get the speed of other vehicles in the session?

**Comment by kutu** [comment]
only by calculating travel distance / time

**Comment by kstrycharz** [comment]
> yes, total time = diff between 2 and 1 but you will need to play with how many ticks you will count, if just use 2 close it will play a lot, 10 is better, but then speed start drifting

So SessionTick should be the value for time..... which updates 60 times a second?

**Comment by kutu** [comment]
doesn't matter, you can use sessiontick or sessiontime
