### ISSUE TITLE
loss of control

### ISSUE THREAD

**Issue by AndiSenior** [kutu/pyirsdk#30]
Hi kutu
Many thanks for the great SDK, it works like a charm:-)
Regarding incidents: there is only the incidents counter in the "DriverInfo" available right?
So, the way to detect the type of incident ist to store the old incident count and subtract the new.
So you get x1, x2 and x4 incidents, right? 
Is there another approach to detect the incidents?
The off track can be detected reading the CarIdxTrackSurface, but how can I detect "loss of control" and "light contact with another driver" (0x0)?
Hope you can give me a direction, thanks in advance, Andi

**Comment by kutu** [comment]
> Is there another approach to detect the incidents?

ir['PlayerCarDriverIncidentCount']
DriverInfo incidents only available after the session ends in race, in practice incidents maybe available immediately

> The off track can be detected reading the CarIdxTrackSurface

not reliable

> but how can I detect "loss of control"

maybe 2x and car slowed down a lot

> "light contact with another driver" (0x0)?

you can't
