### ISSUE TITLE
Chat Example

### ISSUE THREAD

**Issue by AndiSenior** [kutu/pyirsdk#32]
Hi
chat_command(begin_chat) opens a new chat.
But how can I send now a chat message, for instance "clear #22 all your penalties have been cleared'
Thanks for your reply
Andi

**Comment by kutu** [comment]
by sending keystrokes to iracing window

**Comment by AndiSenior** [comment]
Do you have an example?
So far I use win32gui.SendMessage but I can only change the title of the iRacing.com Simulator Window. And there is no other Child Window.
