### ISSUE TITLE
Is there a variable for battery?

### ISSUE THREAD

**Issue by HUSKUT** [kutu/pyirsdk#35]
Hey folks, appreciate the SDK. Its been really nice & well documented so far.

I was wondering if there is a variable (like ir['battery']) for the hybrid battery in cars for the GTP class.
I was unable to find it, maybe it exists or maybe it doesn't. (I assume its just a variable I overlooked)

Again, good work on the repo, its well made :)

**Comment by kutu** [comment]
https://github.com/kutu/pyirsdk/issues/33#issuecomment-1711262491
