### ISSUE TITLE
Read Setup files wth the IBT Class

### ISSUE THREAD

**Issue by byteinsight** [kutu/pyirsdk#36]
Hi,

Thanks for the amazing library.   

Is it possible to read the Setup information from the IBT class as in the C++ version examples?

Thanks Chris

		if (1 == idk.getSessionStrVal("DriverInfo:DriverSetupName:", tstr, MAX_STR))
		{
			printf("CarSetupName: %s", tstr);

			if(1 == idk.getSessionStrVal("DriverInfo:DriverSetupLoadTypeName:", tstr, MAX_STR))
				printf(", %s", tstr);

			if(1 == idk.getSessionStrVal("DriverInfo:DriverSetupIsModified:", tstr, MAX_STR))
				if(atoi(tstr) == 1)
					printf(", modified");

			if(1 == idk.getSessionStrVal("DriverInfo:DriverSetupPassedTech:", tstr, MAX_STR))
				if(atoi(tstr) == 0)
					printf(", failed tech");

			printf("\n");
		}

		// get the current setup and dump it
		const char *sesStr = idk.getSessionStr();
		if(sesStr)
		{
			//****Note, this assumes CarSetup is the last section of the session string.
			const char *tstr = strstr(sesStr, "CarSetup:");
			if(tstr)
			{
				printf(tstr);
				printf("\n");
			}
		}

**Comment by kutu** [comment]
```py
import irsdk

ir = irsdk.IRSDK()
ir.startup(test_file='test.ibt')

print(ir['CarSetup'])
```
