### ISSUE TITLE
IsOnTrackCar and TireRF_RumblePitch

### ISSUE THREAD

**Issue by marcelomanzo** [kutu/pyirsdk#6]
Hi @kutu,

I think something is not right in the latest December build of the iRacing.

The IsOnTrackCar is returning True when the car is not on the track.

The rumble pitch variables (like TireRF_RumblePitch) are always returning 0.

Any idea if they changed the sdk?

**Comment by kutu** [comment]
`IsOnTrackCar` working properly, you probably want to use `IsOnTrack`, read description of those two in vars.txt

i have never used `TireRF_RumblePitch`, so if it doesn't work, report to david tucker
