### ISSUE TITLE
Add support for multiple test files

### ISSUE THREAD

**Issue by JoaoPPinto** [kutu/pyirsdk#8]
Hello,

It would extremely useful to be able to pass several binary files on startup, and have the sdk cycle through them whenever the `freeze_var_buffer_latest()` function is called.
It would allow easier testing of behavior that depends on specific conditions.

Would you review a PR with this feature?

**Comment by JoaoPPinto** [comment]
Thanks for the reply.

I'm using my own project, however I'd be interested in solution suggested for IRBrowserApps server.

**Comment by kutu** [comment]
server can record live telemetry data at 1-60 fps into json file
`server -r 1`

if you quit iracing session, json file will be zipped to reduce space usage

in `ir.coffee` file, there class `IRacing`
pass recorded json file to it when you create an instance of that class

check for variables update with `ir.onUpdate = function(keys) {}`

when `ir.data.connected == true` happens you can invoke
`ir.playRecord(startFrame=0, stopFrame=null, speed=1)`

after that `ir.data.Speed` will have recorded data update at rate of 1fps

check this tutorial example http://ir-apps.kutu.ru/#!/docs

good luck
